{
	"_Type": "Action.Type.BannerMessage",
	"ActionResult": {
		"_Name": "worflowStatusUpdatedFailedMsg"
	},
	"Message": "#ActionResults:getWorflowStatus/error",
	"Duration": 15,
	"Semantic": "Negative"
}